import { createCostCenter, createTask, deleteCostCenter, deleteTask, editTask, logHours, toggleTask } from '@/app/actions'
import { requireRole } from '@/lib/auth'

export default async function Tasker({ searchParams }: { searchParams: Promise<{ month?: string }> }) {
  const params = await searchParams
  const month = /^\d{4}-\d{2}$/.test(params.month || '') ? params.month! : new Date().toISOString().slice(0, 7)
  const startDate = new Date(`${month}-01T00:00:00Z`)
  const endDate = new Date(startDate)
  endDate.setUTCMonth(endDate.getUTCMonth() + 1)
  const startIso = startDate.toISOString()
  const endIso = endDate.toISOString()
  const { supabase, profile } = await requireRole(['admin', 'auditor'])
  const [{ data: tasks }, { data: centers }, { data: tickets }, { data: regs }] = await Promise.all([
    supabase.from('tareas').select('id,nombre,descripcion,incidencia_id,estado,fecha_creacion,fecha_cierre,centro_coste_id,centros:centro_coste_id(nombre)').eq('eliminado', false).order('fecha_creacion', { ascending: false }),
    supabase.from('centros_coste').select('id,nombre').order('nombre'),
    supabase.from('incidencias').select('id,titulo').eq('eliminado', false).order('id', { ascending: false }),
    supabase.from('tarea_registros').select('id,tarea_id,horas,fecha_creacion').gte('fecha_creacion', startIso).lt('fecha_creacion', endIso).order('fecha_creacion', { ascending: false }),
  ])
  const safeTasks = tasks ?? []
  const safeCenters = centers ?? []
  const safeTickets = tickets ?? []
  const safeRegs = regs ?? []
  const totalHours = safeRegs.reduce((sum, row) => sum + Number(row.horas), 0)
  const totals = safeCenters.map(center => ({ name: center.nombre, hours: safeRegs.filter(row => safeTasks.some(task => task.id === row.tarea_id && task.centro_coste_id === center.id)).reduce((sum, row) => sum + Number(row.horas), 0) }))
  return <div className="stack">
    <div className="hero"><div><h1>Tasker</h1><p>Planifica tareas y controla las horas imputadas por centro de coste.</p></div><div className="toolbar-right"><form method="GET" className="row-actions"><input className="input" type="month" name="month" defaultValue={month} /><button className="btn btn-secondary">Aplicar mes</button></form><a className="btn btn-secondary" href={`/api/export/tasker?month=${month}`}>⬇ Exportar</a></div></div>
    <div className="quick-grid"><div className="quick-card"><div className="label">Horas del mes</div><div className="value">{totalHours.toFixed(2)} h</div></div>{totals.slice(0,3).map(x=><div className="quick-card" key={x.name}><div className="label">{x.name}</div><div className="value">{x.hours.toFixed(2)} h</div></div>)}</div>
    {profile.rol === 'admin' && <div className="card pad"><h2 className="section-title">Nueva tarea</h2><form action={createTask} className="form-grid" style={{marginTop:14}}><label>Nombre<input className="input" name="nombre" required /></label><label>Incidencia<select className="input" name="incidencia_id"><option value="">Sin incidencia</option>{safeTickets.map(t=><option key={t.id} value={t.id}>#INC-{String(t.id).padStart(3,'0')} · {t.titulo}</option>)}</select></label><label>Centro de coste<select className="input" name="centro_coste_id"><option value="">Sin asignar</option>{safeCenters.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select></label><label className="full">Descripción<textarea className="input" name="descripcion" rows={3}/></label><button className="btn btn-primary full">Crear tarea</button></form></div>}
    <div className="card"><div className="table-wrap"><table className="table"><thead><tr><th>Tarea</th><th>Incidencia</th><th>Centro</th><th>Horas</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{safeTasks.map((t:any)=>{const hours=(regs||[]).filter(r=>r.tarea_id===t.id).reduce((sum,r)=>sum+Number(r.horas),0);return <tr key={t.id}><td><strong>{t.nombre}</strong><div className="small muted">{t.descripcion}</div></td><td>{t.incidencia_id?`#INC-${String(t.incidencia_id).padStart(3,'0')}`:'—'}</td><td>{t.centros?.nombre||'Sin asignar'}</td><td><strong>{hours.toFixed(2)} h</strong></td><td><span className={`badge ${t.estado==='cerrada'?'green':'blue'}`}>{t.estado}</span></td><td><div className="row-actions">{profile.rol==='admin'&&<><form action={toggleTask.bind(null,t.id,t.estado!=='cerrada')}><button className="btn btn-secondary btn-sm">{t.estado==='cerrada'?'Reabrir':'Cerrar'}</button></form><details><summary className="btn btn-warning btn-sm">Editar</summary><form action={editTask} className="stack" style={{marginTop:8,minWidth:280}}><input type="hidden" name="id" value={t.id}/><input className="input" name="nombre" defaultValue={t.nombre} required/><textarea className="input" name="descripcion" defaultValue={t.descripcion||''}/><select className="input" name="incidencia_id" defaultValue={t.incidencia_id||''}><option value="">Sin incidencia</option>{safeTickets.map(x=><option key={x.id} value={x.id}>#INC-{String(x.id).padStart(3,'0')} · {x.titulo}</option>)}</select><select className="input" name="centro_coste_id" defaultValue={t.centro_coste_id||''}><option value="">Sin asignar</option>{safeCenters.map(c=><option key={c.id} value={c.id}>{c.nombre}</option>)}</select><button className="btn btn-primary">Guardar</button></form></details><form action={deleteTask.bind(null,t.id)}><button className="btn btn-danger btn-sm">Papelera</button></form></>}</div></td></tr>})}</tbody></table>{!safeTasks.length&&<div className="empty">No hay tareas.</div>}</div></div>
    {profile.rol==='admin'&&<div className="grid g2"><div className="card pad"><h2 className="section-title">Imputar horas</h2><form action={logHours} className="stack" style={{marginTop:14}}><label className="stack small"><strong>Tarea</strong><select className="input" name="tarea_id" required>{safeTasks.filter(t=>t.estado!=='cerrada').map(t=><option key={t.id} value={t.id}>{t.nombre}</option>)}</select></label><label className="stack small"><strong>Horas</strong><input className="input" type="number" name="horas" min="0.05" step="0.05" required/></label><label className="stack small"><strong>Comentario</strong><textarea className="input" name="comentario" rows={4} required/></label><button className="btn btn-primary">Registrar horas</button></form></div><div className="card pad"><h2 className="section-title">Centros de coste</h2><form action={createCostCenter} className="row-actions" style={{marginTop:14}}><input className="input" name="nombre" placeholder="Nuevo centro" required/><button className="btn btn-primary">Añadir</button></form><div className="stack" style={{marginTop:14}}>{safeCenters.map(c=><div key={c.id} className="message" style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><span>{c.nombre}</span><form action={deleteCostCenter.bind(null,c.id)}><button className="btn btn-danger btn-sm">Eliminar</button></form></div>)}</div></div></div>}
  </div>
}
