import Link from 'next/link'
import {requireUser} from '@/lib/auth'
export default async function Dashboard(){const {supabase,profile}=await requireUser();const [{count:total},{count:open},{count:process},{data:recent},{data:notes}]=await Promise.all([
 supabase.from('incidencias').select('id',{count:'exact',head:true}).eq('eliminado',false),
 supabase.from('incidencias').select('id',{count:'exact',head:true}).eq('estado','abierta').eq('eliminado',false),
 supabase.from('incidencias').select('id',{count:'exact',head:true}).eq('estado','en_proceso').eq('eliminado',false),
 supabase.from('incidencias').select('id,titulo,estado,fecha_creacion').eq('eliminado',false).order('fecha_creacion',{ascending:false}).limit(6),
 supabase.from('notificaciones').select('id,titulo,mensaje,enlace,creada_at').eq('usuario_id',profile.id).is('leida_at',null).order('creada_at',{ascending:false}).limit(5)
]);
 return <div className="stack"><div className="toolbar"><div><h1 style={{margin:'0 0 4px'}}>Buenos días, {profile.nombre.split(' ')[0]} 👋</h1><div className="muted">Resumen del portal de soporte.</div></div><Link href="/tickets" className="btn btn-primary">🎫 Ver incidencias</Link></div><div className="grid g4"><div className="card pad"><div className="stat-label">Total incidencias</div><div className="stat-value">{total??0}</div></div><div className="card pad"><div className="stat-label">Abiertas</div><div className="stat-value" style={{color:'#dc2626'}}>{open??0}</div></div><div className="card pad"><div className="stat-label">En proceso</div><div className="stat-value" style={{color:'#d97706'}}>{process??0}</div></div><div className="card pad"><div className="stat-label">Pendientes personales</div><div className="stat-value">{notes?.length??0}</div></div></div><div className="grid g2"><div className="card pad"><h2 style={{marginTop:0}}>Incidencias recientes</h2>{recent?.length?recent.map(t=><Link key={t.id} href={`/tickets/${t.id}`} className="message" style={{display:'block',marginBottom:8}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><strong>#{String(t.id).padStart(3,'0')} · {t.titulo}</strong><span className={`badge ${t.estado==='abierta'?'red':t.estado==='en_proceso'?'amber':'green'}`}>{t.estado.replace('_',' ')}</span></div><div className="small muted">{new Date(t.fecha_creacion).toLocaleString('es-ES')}</div></Link>):<div className="empty">No hay incidencias.</div>}</div><div className="card pad"><h2 style={{marginTop:0}}>Notificaciones</h2>{notes?.length?notes.map(n=><Link key={n.id} href={n.enlace||'#'} className="message" style={{display:'block',marginBottom:8}}><strong>{n.titulo}</strong><div className="small muted">{n.mensaje}</div></Link>):<div className="empty">No tienes notificaciones pendientes.</div>}</div></div></div>}
