import { assignEquipment, createEquipment, deleteEquipment, editEquipment, releaseEquipment } from '@/app/actions'
import { AssignEquipmentForm } from '@/components/assign-equipment-form'
import { requireUser } from '@/lib/auth'

export default async function Material() {
  const { supabase, profile } = await requireUser()
  const [{ data: items }, { data: users }] = await Promise.all([
    supabase.from('equipos').select('id,tipo,marca,modelo,identificador,estado_equipo,observaciones,usuario_id,usuarios:usuario_id(nombre),centros:centro_coste_id(nombre)').order('tipo').order('marca'),
    supabase.from('usuarios').select('id,nombre,email').eq('estado_cuenta', 'activo').order('nombre'),
  ])
  const safeItems = items ?? []
  const safeUsers = users ?? []
  const staff = ['admin', 'controller'].includes(profile.rol)
  return <div className="stack"><div className="hero"><div><h1>Inventario</h1><p>Equipos, asignaciones y estado del material IT.</p></div><span className="badge blue">{safeItems.length} equipos</span></div>
    {staff && <div className="card pad"><h2 className="section-title">Dar de alta equipo</h2><p className="section-subtitle">Se guarda inicialmente como «En stock».</p><form action={createEquipment} className="form-grid" style={{marginTop:14}}><label>Tipo<select className="input" name="tipo"><option value="portatil">Portátil</option><option value="movil">Móvil</option><option value="telefono">Teléfono</option><option value="periferico">Periférico</option><option value="otro">Otro</option></select></label><label>Marca<input className="input" name="marca" required /></label><label>Modelo<input className="input" name="modelo" required /></label><label>Identificador / S/N<input className="input" name="identificador" required /></label><label className="full">Observaciones<textarea className="input" name="observaciones" rows={3} /></label><button className="btn btn-primary full">Dar de alta</button></form></div>}
    <div className="card"><div className="table-wrap"><table className="table"><thead><tr><th>Tipo</th><th>Equipo</th><th>S/N</th><th>Usuario</th><th>Centro</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{safeItems.map((e:any)=><tr key={e.id}><td>{e.tipo}</td><td><strong>{e.marca} {e.modelo}</strong><div className="small muted">{e.observaciones}</div></td><td><code>{e.identificador}</code></td><td>{e.usuarios?.nombre || 'Sin asignar'}</td><td>{e.centros?.nombre || 'Sin asignar'}</td><td><span className={`badge ${e.estado_equipo==='en_stock'?'green':e.estado_equipo==='asignado'?'blue':e.estado_equipo==='reparacion'?'amber':'red'}`}>{e.estado_equipo.replace('_',' ')}</span></td><td>{staff && <div className="row-actions">{e.usuario_id ? <form action={releaseEquipment.bind(null,e.id,'en_stock')}><button className="btn btn-secondary btn-sm">Liberar</button></form> : <AssignEquipmentForm equipmentId={e.id} users={safeUsers as any} />}<details><summary className="btn btn-warning btn-sm">Editar</summary><form action={editEquipment} className="stack" style={{marginTop:8,minWidth:260}}><input type="hidden" name="id" value={e.id}/><select className="input" name="tipo" defaultValue={e.tipo}><option value="portatil">Portátil</option><option value="movil">Móvil</option><option value="telefono">Teléfono</option><option value="periferico">Periférico</option><option value="otro">Otro</option></select><input className="input" name="marca" defaultValue={e.marca} required/><input className="input" name="modelo" defaultValue={e.modelo} required/><input className="input" name="identificador" defaultValue={e.identificador} required/><select className="input" name="estado_equipo" defaultValue={e.estado_equipo}><option value="en_stock">En stock</option><option value="asignado">Asignado</option><option value="reparacion">Reparación</option><option value="baja">Baja</option></select><textarea className="input" name="observaciones" defaultValue={e.observaciones||''}/><button className="btn btn-primary">Guardar</button></form></details><form action={deleteEquipment.bind(null,e.id)}><button className="btn btn-danger btn-sm">Borrar</button></form></div>}</td></tr>)}</tbody></table>{!safeItems.length&&<div className="empty">No hay equipos registrados.</div>}</div></div>
  </div>
}
